// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3fOKrlj7huv5skKhk75mN_vZWgkbGfY4',
    appId: '1:558233372737:web:ff67228e2560592a485ec0',
    messagingSenderId: '558233372737',
    projectId: 'personal-expenses-d5cec',
    authDomain: 'personal-expenses-d5cec.firebaseapp.com',
    storageBucket: 'personal-expenses-d5cec.firebasestorage.app',
    measurementId: 'G-SFTENMG52Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9iKet1obM5DbKK3WoRdrkJh9ki2hxMnA',
    appId: '1:558233372737:android:8f107a3c03a51fc5485ec0',
    messagingSenderId: '558233372737',
    projectId: 'personal-expenses-d5cec',
    storageBucket: 'personal-expenses-d5cec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBia0SnJhPgK69zkhDsBRfBA99MfWWOQaU',
    appId: '1:558233372737:ios:2fef3e4bb2235587485ec0',
    messagingSenderId: '558233372737',
    projectId: 'personal-expenses-d5cec',
    storageBucket: 'personal-expenses-d5cec.firebasestorage.app',
    androidClientId: '558233372737-gbrkshm2amc8qg0nast68u15vpios1ue.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalExpenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBia0SnJhPgK69zkhDsBRfBA99MfWWOQaU',
    appId: '1:558233372737:ios:2fef3e4bb2235587485ec0',
    messagingSenderId: '558233372737',
    projectId: 'personal-expenses-d5cec',
    storageBucket: 'personal-expenses-d5cec.firebasestorage.app',
    androidClientId: '558233372737-gbrkshm2amc8qg0nast68u15vpios1ue.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalExpenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3fOKrlj7huv5skKhk75mN_vZWgkbGfY4',
    appId: '1:558233372737:web:7821ef969dc717a2485ec0',
    messagingSenderId: '558233372737',
    projectId: 'personal-expenses-d5cec',
    authDomain: 'personal-expenses-d5cec.firebaseapp.com',
    storageBucket: 'personal-expenses-d5cec.firebasestorage.app',
    measurementId: 'G-B9JTBNCEFQ',
  );

}